USE [DocumentRequestData]
GO
/****** Object:  Table [dbo].[RD_RequestLog]    Script Date: 03/12/2014 11:05:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[RD_RequestLog](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Entity] [varchar](150) NULL,
	[DocumentType] [varchar](150) NULL,
	[Service] [varchar](150) NULL,
	[Sender] [varchar](150) NULL,
	[SubmittedAt] [datetime] NULL,
	[Comments] [varchar](max) NULL,
 CONSTRAINT [PK_RD_RequestLog] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET IDENTITY_INSERT [dbo].[RD_RequestLog] ON
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (1, N'US Entity #1 LTD', N'Certificate of Incumbency', N'Order - Express', N'john.doe@yahoo.com', CAST(0x0000A2BD011D396B AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (2, N'US Entity #1 LTD', N'Certificate of Incumbency', N'Order - Express', N'john.doe@yahoo.com', CAST(0x0000A2BD011D3A56 AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (3, N'US Entity #1 LTD', N'Certificate of Existence', N'Order - Express', N'john.doe@yahoo.com', CAST(0x0000A2BD012E8F22 AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (4, N'US Entity #1 LTD', N'Certificate of Incumbency', N'Order - Normal', N'john.doe@yahoo.com', CAST(0x0000A2BD0131CA7C AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (5, N'UK Entity #7 LTD', N'Certificate of Incumbency', N'Express Service', N'john.doe@yahoo.com', CAST(0x0000A2C100B930B7 AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (6, N'UK Entity #7 LTD', N'Register of Officers', N'Certified by Registrar - Normal Service', N'john.doe@yahoo.com', CAST(0x0000A2C200FD1E3D AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (7, N'UK Entity #9 LP', N'Memorandum and Articles of Association', N'Certified by Registrar - Express Service (24 Hours)', N'john.doe@yahoo.com', CAST(0x0000A2C201124A02 AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (8, N'US Entity #1 LTD', N'Register of Mortgages and Charges', N'Certified by Registrar - Express Service (24 Hours)', N'john.doe@yahoo.com', CAST(0x0000A2C2011418BA AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (9, N'UK Entity #9 LP', N'Memorandum and Articles of Association', N'Certified by Registered Office', N'john.doe@yahoo.com', CAST(0x0000A2C201155097 AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (10, N'US Entity #1 LTD', N'Register of Shareholders', N'Certified by Registrar - Normal Service', N'john.doe@yahoo.com', CAST(0x0000A2C2012E9989 AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (11, N'US Entity #1 LTD', N'Register of Shareholders', N'Certified by Registrar - Express Service (24 Hours)', N'john.doe@yahoo.com', CAST(0x0000A2C2013361AB AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (12, N'US Entity #234 LTD', N'Register of Shareholders', N'Certified by Registered Office', N'john.doe@yahoo.com', CAST(0x0000A2C2013CF82D AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (13, N'Unspecified Entity #90 LP', N'Register of Mortgages and Charges', N'Certified by Registrar - Express Service (24 Hours)', N'john.doe@yahoo.com', CAST(0x0000A2C700D3B8AD AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (14, N'UK Entity #9 LP', N'Certificate of Incorporation/Registration', N'Certified by Registrar - Express Service (24 Hours)', N'john.doe@yahoo.com', CAST(0x0000A2C700D89641 AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (15, N'Company #12 Corporate Services LTD', N'Register of Mortgages and Charges', N'Authenticated / Apostilled', N'john.doe@yahoo.com', CAST(0x0000A2C700D8F5DB AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (16, N'Unspecified Entity #90 LP', N'Certificate of Good Standing', N'Standard Service', N'john.doe@yahoo.com', CAST(0x0000A2C700F1DE86 AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (17, N'Company #58 Corporate Services LP', N'Certificate of Incorporation/Registration', N'Certified by Registered Office', N'john.doe@yahoo.com', CAST(0x0000A2C700F95B2C AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (18, N'Company #8 Asset Management LTD', N'Register of Shareholders', N'Certified by Registered Office', N'john.doe@yahoo.com', CAST(0x0000A2C70119B9AE AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (19, N'UK Entity #9 LP', N'Certificate of Incorporation/Registration', N'Certified by Registered Office', N'joe.shmoe@gmail.com', CAST(0x0000A2C800F03B70 AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (20, N'UK Entity #9 LP', N'Certificate of Existence', N'Express Service', N'joe.shmoe@gmail.com', CAST(0x0000A2C800F3D592 AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (21, N'UK Entity #7 LTD', N'Registered Office Certificate', N'Express Service', N'joe.shmoe@gmail.com', CAST(0x0000A2C8012EBF99 AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (22, N'Trading Company #4 LTD', N'Tax Undertaking Certificate', N'Legalised', N'joe.shmoe@gmail.com', CAST(0x0000A2CA00CB32D4 AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (23, N'Unspecified Entity #90 LP', N'Certificate of Incumbency', N'Standard Service', N'joe.shmoe@gmail.com', CAST(0x0000A2CA00CE06A1 AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (24, N'Trading Company #634 LP', N'Certificate of Incumbency', N'Express Service', N'joe.shmoe@gmail.com', CAST(0x0000A2CA00F3F823 AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (25, N'Unspecified Entity #90 LP', N'Register of Mortgages and Charges', N'Authenticated / Apostilled', N'joe.shmoe@gmail.com', CAST(0x0000A2CA00F52921 AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (26, N'Trading Company #4 LTD', N'Certificate of Incumbency', N'Standard Service', N'joe.shmoe@gmail.com', CAST(0x0000A2CA00F85AAA AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (27, N'Company ABC Asset Management LTD', N'Registered Office Certificate', N'Express Service', N'joe.shmoe@gmail.com', CAST(0x0000A2CA00FAFAAB AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (28, N'Company XYZ Corporate Services LP', N'Register of Mortgages and Charges', N'Certified by Registrar - Express Service (24 Hours)', N'joe.shmoe@gmail.com', CAST(0x0000A2CB00F87609 AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (29, N'Limited Company #209', N'Certificate of Incumbency', N'Express Service', N'joe.shmoe@gmail.com', CAST(0x0000A2CB00FA2464 AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (30, N'Company #12 Corporate Services LTD', N'Certificate of Incorporation/Registration', N'Certified by Registrar - Normal Service', N'joe.shmoe@gmail.com', CAST(0x0000A2CB0106CD00 AS DateTime), N'These are some comments I have about the request I am making.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (31, N'Limited Company #209', N'Certificate of Incorporation/Registration', N'Certified by Registrar - Express Service (24 Hours)', N'joe.shmoe@gmail.com', CAST(0x0000A2CB01083DE5 AS DateTime), N'(No comments)')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (32, N'Limited Company #209', N'Certificate of Incumbency', N'Express Service', N'joe.shmoe@gmail.com', CAST(0x0000A2CB010A6F61 AS DateTime), N'(No comments)')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (33, N'Limited Company #209', N'Certificate of Incumbency', N'Express Service', N'joe.shmoe@gmail.com', CAST(0x0000A2CB010AA1E6 AS DateTime), N'(No comments)')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (34, N'Company #12 Corporate Services LTD', N'Certificate of Incumbency', N'Express Service', N'joe.shmoe@gmail.com', CAST(0x0000A2CE00A3D64C AS DateTime), N'(No comments)')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (35, N'Company XYZ Corporate Services LP', N'Certificate of Incorporation/Registration', N'Certified by Registered Office', N'joe.shmoe@gmail.com', CAST(0x0000A2CE00C7EB8C AS DateTime), N'(No comments)')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (36, N'Company XYZ Corporate Services LP', N'Certificate of Incorporation/Registration', N'Certified by Registered Office', N'joe.shmoe@gmail.com', CAST(0x0000A2CE00E68E0A AS DateTime), N'(No comments)')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (37, N'UK Company #44 Corporate Services LTD', N'Certificate of Incumbency', N'Standard Service', N'joe.shmoe@gmail.com', CAST(0x0000A2CE00F83206 AS DateTime), N'(No comments)')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (38, N'US Entity #234 LTD', N'Certificate of Good Standing', N'Order', N'john.doe@yahoo.com', CAST(0x0000A2CF0108A8A4 AS DateTime), N'(No comments)')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (39, N'Trading Company #634 LP', N'Certificate of Good Standing', N'Order', N'john.doe@yahoo.com', CAST(0x0000A2CF012BC4BB AS DateTime), N'(No comments)')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (40, N'Company XYZ Corporate Services LTD', N'Certificate of Incumbency', N'Standard Service', N'joe.shmoe@gmail.com', CAST(0x0000A2D000F90885 AS DateTime), N'(No comments)')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (41, N'Company XYZ Corporate Services LP', N'Tax Exemption Certificate', N'Authenticated / Apostilled', N'joe.shmoe@gmail.com', CAST(0x0000A2D000FB4CA1 AS DateTime), N'(No comments)')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (42, N'UK Entity #9 LP', N'Certificate of Incorporation/Registration', N'Certified by Registrar - Normal Service', N'john.doe@yahoo.com', CAST(0x0000A2D0012B8B81 AS DateTime), N'(No comments)')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (43, N'Company XYZ Corporate Services LP', N'Certificate of Incumbency', N'Order', N'john.doe@yahoo.com', CAST(0x0000A2D0012D14D1 AS DateTime), N'Thank you for processing my request. I hope to receive my copy of the document soon.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (44, N'Company XYZ Directors LTD', N'Certificate of Good Standing', N'Standard Service', N'john.doe@yahoo.com', CAST(0x0000A2D00137C6F4 AS DateTime), N'Thank you for processing my request. I hope to receive my copy of the document soon.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (45, N'Company #5 Fund LTD', N'Certificate of Incorporation/Registration', N'Certified by Registered Office', N'john.doe@yahoo.com', CAST(0x0000A2D200DF00C4 AS DateTime), N'Thank you for processing my request. I hope to receive my copy of the document soon.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (46, N'Company #5 Fund LTD', N'Register of Directors', N'Certified by Registered Office', N'john.doe@yahoo.com', CAST(0x0000A2D200F210F8 AS DateTime), N'Thank you for processing my request. I hope to receive my copy of the document soon.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (47, N'Company #5 Fund LTD', N'Register of Directors', N'Certified by Registered Office', N'john.doe@yahoo.com', CAST(0x0000A2D200F45C43 AS DateTime), N'Thank you for processing my request. I hope to receive my copy of the document soon.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (48, N'Company #5 Fund LTD', N'Register of Officers', N'Certified by Registrar - Normal Service', N'john.doe@yahoo.com', CAST(0x0000A2D200FFC340 AS DateTime), N'Thank you for processing my request. I hope to receive my copy of the document soon.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (49, N'UK Company #977 Corporate Services LTD', N'Certificate of Incumbency', N'Express Service', N'john.doe@yahoo.com', CAST(0x0000A2D201007963 AS DateTime), N'Thank you for processing my request. I hope to receive my copy of the document soon.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (50, N'US Company #3 Corporate Services LP', N'Register of Mortgages and Charges', N'Certified by Registered Office', N'john.doe@yahoo.com', CAST(0x0000A2D20107FC45 AS DateTime), N'Thank you for processing my request. I hope to receive my copy of the document soon.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (51, N'UK Company ABC LP', N'Certificate of Incorporation/Registration', N'Legalised', N'john.doe@yahoo.com', CAST(0x0000A2D2010968F5 AS DateTime), N'Thank you for processing my request. I hope to receive my copy of the document soon.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (52, N'Unspecified Offshore Entity #9 LTD', N'Certificate of Incumbency', N'Express Service', N'john.doe@yahoo.com', CAST(0x0000A2D2010B6E2F AS DateTime), N'Thank you for processing my request. I hope to receive my copy of the document soon.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (53, N'UK Company ABC LP', N'Certificate of Existence', N'Express Service', N'john.doe@yahoo.com', CAST(0x0000A2D20118ADC3 AS DateTime), N'Thank you for processing my request. I hope to receive my copy of the document soon.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (54, N'US Company #32 Corporate Services LP', N'Certificate of Incorporation/Registration', N'Certified by Registrar - Express Service (24 Hours)', N'john.doe@yahoo.com', CAST(0x0000A2D201196A15 AS DateTime), N'Thank you for processing my request. I hope to receive my copy of the document soon.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (55, N'Unspecified Offshore Entity #9 LTD', N'Certificate of Incumbency', N'Standard Service', N'john.doe@yahoo.com', CAST(0x0000A2D2011A6AC4 AS DateTime), N'Thank you for processing my request. I hope to receive my copy of the document soon.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (56, N'Company ABC Asset Management LTD', N'Certificate of Incorporation/Registration', N'Certified by Registered Office', N'john.doe@yahoo.com', CAST(0x0000A2D2012B0DFB AS DateTime), N'Thank you for processing my request. I hope to receive my copy of the document soon.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (57, N'Trading Company #634 LP', N'Certificate of Good Standing', N'Standard Service', N'joe.shmoe@gmail.com', CAST(0x0000A2D600C9D084 AS DateTime), N'Thank you for processing my request. I hope to receive my copy of the document soon.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (58, N'Company #54 Offshore Fund LTD', N'Certificate of Incumbency', N'Express Service', N'john.doe@yahoo.com', CAST(0x0000A2D700D480F5 AS DateTime), N'Thank you for processing my request. I hope to receive my copy of the document soon.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (59, N'UK Entity #12 LP', N'Certificate of Incorporation/Registration', N'Certified by Registrar - Normal Service', N'john.doe@yahoo.com', CAST(0x0000A2D700D5A066 AS DateTime), N'Thank you for processing my request. I hope to receive my copy of the document soon.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (60, N'UK Entity #67 Partners LTD', N'Certificate of Incumbency', N'Standard Service', N'john.doe@yahoo.com', CAST(0x0000A2D700DED203 AS DateTime), N'Thank you for processing my request. I hope to receive my copy of the document soon.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (61, N'Company #54 Offshore Fund LTD', N'Certificate of Good Standing', N'Standard Service', N'john.doe@yahoo.com', CAST(0x0000A2D700DF5994 AS DateTime), N'Thank you for processing my request. I hope to receive my copy of the document soon.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (62, N'Company #5 Asset Management LP', N'Certificate of Incumbency', N'Standard Service', N'john.doe@yahoo.com', CAST(0x0000A2D700E0CB15 AS DateTime), N'Thank you for processing my request. I hope to receive my copy of the document soon.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (63, N'Company #5 Asset Management LP', N'Certificate of Incumbency', N'Express Service', N'john.doe@yahoo.com', CAST(0x0000A2D700E464B6 AS DateTime), N'Thank you for processing my request. I hope to receive my copy of the document soon.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (64, N'UK Entity #12 LP', N'Certificate of Existence', N'Express Service', N'john.doe@yahoo.com', CAST(0x0000A2D700E6D6E1 AS DateTime), N'Thank you for processing my request. I hope to receive my copy of the document soon.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (65, N'UK Entity #67 Partners LTD', N'Certificate of Incumbency', N'Standard Service', N'john.doe@yahoo.com', CAST(0x0000A2D700E75A69 AS DateTime), N'Thank you for processing my request. I hope to receive my copy of the document soon.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (66, N'Company #5 Asset Management LP', N'Register of Mortgages and Charges', N'Certified by Registrar - Express Service (24 Hours)', N'john.doe@yahoo.com', CAST(0x0000A2D700E7CAA0 AS DateTime), N'Thank you for processing my request. I hope to receive my copy of the document soon.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (67, N'US Entity #888 Partners LP', N'Certificate of Good Standing', N'Express Service', N'john.doe@yahoo.com', CAST(0x0000A2D700F28E2C AS DateTime), N'Thank you for processing my request. I hope to receive my copy of the document soon.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (68, N'UK Entity #12 LP', N'Certificate of Incorporation/Registration', N'Certified by Registered Office', N'john.doe@yahoo.com', CAST(0x0000A2D7010DEA0A AS DateTime), N'Thank you for processing my request. I hope to receive my copy of the document soon.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (69, N'Company #54 Offshore Fund LTD', N'Certificate of Incorporation/Registration', N'Authenticated / Apostilled', N'john.doe@yahoo.com', CAST(0x0000A2D7010FD543 AS DateTime), N'(No comments)')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (70, N'Unspecified Entity #90 LP', N'Registered Office Certificate', N'Express Service', N'joe.shmoe@gmail.com', CAST(0x0000A2D90099DF4A AS DateTime), N'(No comments)')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (71, N'UK Entity #7 Corporate Services LP', N'Certificate of Incumbency', N'Express Service', N'joe.shmoe@gmail.com', CAST(0x0000A2D9009D768D AS DateTime), N'(No comments)')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (72, N'Unspecified Entity #12 Corporate Services LP', N'Certificate of Incorporation/Registration', N'Notarised', N'joe.shmoe@gmail.com', CAST(0x0000A2D9009FE26B AS DateTime), N'(No comments)')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (73, N'Company #5 Asset Management LP', N'Certificate of Incorporation/Registration', N'Certified by Registered Office', N'john.doe@yahoo.com', CAST(0x0000A2DC00F0E6F4 AS DateTime), N'(No comments)')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (74, N'UK Entity #777 Partners LP', N'Certificate of Incorporation/Registration', N'Certified by Registered Office', N'john.doe@yahoo.com', CAST(0x0000A2DD00F75F92 AS DateTime), N'(No comments)')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (75, N'UK Entity #777 Partners LP', N'Tax Undertaking Certificate', N'Certified by Registrar - Normal Service', N'john.doe@yahoo.com', CAST(0x0000A2DE00B0AA0A AS DateTime), N'(No comments)')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (76, N'Company #5 Asset Management LP', N'Registered Office Certificate', N'Standard Service', N'john.doe@yahoo.com', CAST(0x0000A2DE00B595AE AS DateTime), N'I will be requesting several more copies.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (77, N'Trading Company #4 LTD', N'Other', N'Notary Certified Copy', N'john.doe@yahoo.com', CAST(0x0000A2DE00B69EF7 AS DateTime), N'I will be requesting several more copies.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (78, N'US Company #3 Corporate Services LP', N'Register of Shareholders', N'Notarised', N'john.doe@yahoo.com', CAST(0x0000A2DE00E577D2 AS DateTime), N'I will be requesting several more copies.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (79, N'US Company #3 Corporate Services LP', N'Register of Shareholders', N'Authenticated / Apostilled', N'john.doe@yahoo.com', CAST(0x0000A2DE00EE0D66 AS DateTime), N'I will be requesting several more copies.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (80, N'US Company #3 Corporate Services LP', N'Register of Shareholders', N'Certified by Registrar - Express Service (24 Hours)', N'john.doe@yahoo.com', CAST(0x0000A2DE00F3D4C4 AS DateTime), N'I will be requesting several more copies.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (81, N'US Company #3 Corporate Services LP', N'Register of Shareholders', N'Certified by Registrar - Express Service (24 Hours)', N'john.doe@yahoo.com', CAST(0x0000A2DE00F53951 AS DateTime), N'I will be requesting several more copies.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (82, N'US Company #3 Corporate Services LP', N'Register of Shareholders', N'Authenticated / Apostilled', N'john.doe@yahoo.com', CAST(0x0000A2DE00FA79AB AS DateTime), N'I will be requesting several more copies.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (83, N'UK Company ABC LP', N'Section 9 Statement', N'Notarised', N'john.doe@yahoo.com', CAST(0x0000A2DE00FF6ED2 AS DateTime), N'I will be requesting several more copies.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (84, N'Unspecified Entity #11 Fund LTD', N'Certificate of Formation', N'Not Certified', N'john.doe@yahoo.com', CAST(0x0000A2DE01578CAC AS DateTime), N'I will be requesting several more copies.')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (85, N'UK Entity #9 LP', N'Tax Undertaking Certificate', N'Certified by Registrar - Express Service (24 Hours)', N'joe.shmoe@gmail.com', CAST(0x0000A2DF0143C06E AS DateTime), N'(No comments)')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (86, N'Company #58 Corporate Services LP', N'Certificate of Incumbency', N'Express Service', N'joe.shmoe@gmail.com', CAST(0x0000A2E0010EB5ED AS DateTime), N'(No comments)')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (87, N'Company #8 Asset Management LTD', N'Register of Shareholders', N'Certified by Registrar - Express Service (24 Hours)', N'joe.shmoe@gmail.com', CAST(0x0000A2E0011A25C7 AS DateTime), N'(No comments)')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (88, N'UK Entity #7 LTD', N'Change of Name Certificate', N'Certified by Registrar - Normal Service', N'joe.shmoe@gmail.com', CAST(0x0000A2E0014190EC AS DateTime), N'(No comments)')
INSERT [dbo].[RD_RequestLog] ([ID], [Entity], [DocumentType], [Service], [Sender], [SubmittedAt], [Comments]) VALUES (89, N'Unspecified Entity #10 Fund LTD', N'Register of Mortgages and Charges', N'Certified by Registered Office', N'john.doe@yahoo.com', CAST(0x0000A2E300D98EC3 AS DateTime), N'(No comments)')
SET IDENTITY_INSERT [dbo].[RD_RequestLog] OFF
