USE [master]
GO

/****** Object:  Database [DocumentRequestData]    Script Date: 03/12/2014 10:56:33 ******/
CREATE DATABASE [DocumentRequestData] ON  PRIMARY 
( NAME = N'RequestDocumentData', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\DocumentRequestData.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DocumentRequestData_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\DocumentRequestData_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DocumentRequestData] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DocumentRequestData].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DocumentRequestData] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DocumentRequestData] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DocumentRequestData] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DocumentRequestData] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DocumentRequestData] SET ARITHABORT OFF 
GO

ALTER DATABASE [DocumentRequestData] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DocumentRequestData] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DocumentRequestData] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DocumentRequestData] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DocumentRequestData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DocumentRequestData] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DocumentRequestData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DocumentRequestData] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DocumentRequestData] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DocumentRequestData] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DocumentRequestData] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DocumentRequestData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DocumentRequestData] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DocumentRequestData] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DocumentRequestData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DocumentRequestData] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DocumentRequestData] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DocumentRequestData] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DocumentRequestData] SET  READ_WRITE 
GO

ALTER DATABASE [DocumentRequestData] SET RECOVERY FULL 
GO

ALTER DATABASE [DocumentRequestData] SET  MULTI_USER 
GO

ALTER DATABASE [DocumentRequestData] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DocumentRequestData] SET DB_CHAINING OFF 
GO


